THORSANVIL_ROOT				?= $(realpath ../../)
TARGET						= NisseMCP.slib

FILE_WARNING_FLAGS			+= -Wno-missing-braces
LINK_LIBS					+= Nisse ThorsLogging
UNITTEST_LINK_LIBS			+= Nisse ThorsLogging


include $(THORSANVIL_ROOT)/build/tools/Makefile
